apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
        - cluster: cluster-a
          url: https://kubernetes.default.svc
        - cluster: cluster-b
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/nebbie-corporation/argocd.git
        targetRevision: HEAD
        path: app1
      destination:
        server: '{{url}}'
        namespace: guestbook-{{cluster}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true